on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 1-17/1 * * *'

jobs:
  notion2markdown:
    runs-on: ubuntu-latest
    name: Convert Notion to Markdown
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Convert Notion to Markdown
        id: notion2markdown
        uses: Doradx/notion2markdown-action@v1
        with:
          notion_secret: ${{ secrets.NOTION_SECRET }}
          database_id: "41b9624e2bc8441fb77642dd23155e68"


  

      - name: Install Tree Command
        run: sudo apt-get install tree -y

      - name: Print Directory Structure and Markdown Files
        run: |
          echo "Printing directory structure:"
          tree
          echo "Printing contents of Markdown files:"
          find . -name '*.md' -exec cat {} +
